export interface PaymentAuthorization {
  readonly authId: string;              // unique authorization id
  readonly txId: string;                // transaction id
  readonly senderWalletId: string;
  readonly receiverWalletId: string;

  readonly amountMinor: number;
  readonly currency: string;

  readonly createdAt: string;
  readonly expiresAt: string;

  /**
   * Signature over canonical authorization payload.
   * Generated by server, verified before execution.
   */
  readonly signature: string;
}

export type AuthorizationStatus = "issued" | "used" | "expired" | "revoked";

export interface StoredPaymentAuthorization extends PaymentAuthorization {
  readonly status: AuthorizationStatus;
  readonly usedAt?: string;
  readonly releasedAt?: string;
}
